# This workflow will upload an esptool Python package when a release is created

name: PyPI release

on:
  release:
    types: [released]

jobs:
  build_and_upload:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools twine
    - name: Build and upload esptool ${{ github.event.release.tag_name }}
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        PUBLISHED_VERSION=$(curl https://pypi.org/pypi/esptool/json 2>/dev/null | jq -r '.info.version')
        CURRENT_VERSION=$(python setup.py --version 2>/dev/null)

        if [ "$PUBLISHED_VERSION" == "$CURRENT_VERSION" ]; then
          echo "Version ${PUBLISHED_VERSION} already published, skipping..."
          exit 1
        else
          echo "Packaging and publishing new esptool version: ${CURRENT_VERSION}"
          python setup.py sdist
          tar -ztvf dist/*
          twine upload dist/*
        fi
