#ifndef INTERFACE_H
#define INTERFACE_H

enum SUPER_MESSAGE_TYPE
{
    SUPER_MESSAGE_WIFI_CONN = 0, // 开启连接
    SUPER_MESSAGE_WIFI_AP,       // 开启AP事件
    SUPER_MESSAGE_WIFI_ALIVE,    // wifi开关的心跳维持
    SUPER_MESSAGE_WIFI_DISCONN,  // 连接断开
    SUPER_MESSAGE_UPDATE_TIME,
    SUPER_MESSAGE_GET_PARAM, // 获取参数
    SUPER_MESSAGE_SET_PARAM, // 设置参数
    SUPER_MESSAGE_READ_CFG,  // 向磁盘读取参数
    SUPER_MESSAGE_WRITE_CFG, // 向磁盘写入参数
    SUPER_MESSAGE_MQTT_DATA, // MQTT客户端收到消息

    SUPER_MESSAGE_NONE
};

#endif