"""Play a binary PWM Song file on Windows for a quick audio preview.

The file format is a sequence of little-endian uint16 pairs::

    [frequency_hz][duration_ms]

Frequency 0 is treated as a rest. The script uses ``winsound.Beep`` and
therefore does not require any third-party audio package on Windows.
"""

import argparse
import math
import struct
import sys
import tempfile
import time
import wave
from pathlib import Path
from typing import List, Tuple


Record = Tuple[int, int]
RECORD_STRUCT = struct.Struct("<HH")


def read_pwmsong(path: Path) -> List[Record]:
    """Read and validate a binary PWM Song file."""
    data = path.read_bytes()
    if not data:
        raise ValueError(f"PWM Song file is empty: {path}")
    if len(data) % RECORD_STRUCT.size:
        raise ValueError(
            f"Invalid PWM Song size ({len(data)} bytes); "
            f"it must be a multiple of {RECORD_STRUCT.size}"
        )

    records = list(RECORD_STRUCT.iter_unpack(data))
    for index, (frequency, duration) in enumerate(records):
        if duration == 0:
            raise ValueError(f"Record {index} has a zero duration")
        if frequency > 32767:
            raise ValueError(f"Record {index} frequency is not playable by Windows: {frequency} Hz")
    return records


def _write_preview_wav(records: List[Record], path: Path, sample_rate: int = 44100) -> None:
    """Render PWM Song records as a normal PCM WAV preview."""
    with wave.open(str(path), "wb") as wav_file:
        wav_file.setnchannels(1)
        wav_file.setsampwidth(2)
        wav_file.setframerate(sample_rate)

        for frequency, duration in records:
            sample_count = max(1, int(round(sample_rate * duration / 1000.0)))
            if frequency == 0:
                wav_file.writeframes(b"\x00\x00" * sample_count)
                continue

            phase_step = 2.0 * math.pi * frequency / sample_rate
            samples = bytearray()
            fade_samples = min(int(sample_rate * 0.003), sample_count // 2)
            for index in range(sample_count):
                envelope = 0.35
                if fade_samples:
                    if index < fade_samples:
                        envelope *= index / fade_samples
                    elif index >= sample_count - fade_samples:
                        envelope *= (sample_count - index - 1) / fade_samples
                sample = int(32767.0 * envelope * math.sin(phase_step * index))
                samples.extend(struct.pack("<h", sample))
            wav_file.writeframes(bytes(samples))


def _play_with_beep(records: List[Record], repeat: int) -> None:
    """Play records directly with winsound.Beep for troubleshooting."""
    if sys.platform != "win32":
        raise RuntimeError("This player currently requires Windows (winsound.Beep)")

    import winsound

    count = 0
    while repeat == 0 or count < repeat:
        count += 1
        for index, (frequency, duration) in enumerate(records):
            print(
                f"[{index + 1:4}/{len(records)}] "
                f"{frequency:5} Hz  {duration:5} ms",
                end="\r",
                flush=True,
            )
            if frequency == 0:
                time.sleep(duration / 1000.0)
            else:
                winsound.Beep(frequency, duration)
    print()


def play_pwmsong(records: List[Record], repeat: int = 1, use_beep: bool = False) -> None:
    """Play a PWM Song through the normal Windows audio device."""
    if sys.platform != "win32":
        raise RuntimeError("This player currently requires Windows")

    if use_beep:
        _play_with_beep(records, repeat)
        return

    import winsound

    with tempfile.TemporaryDirectory(prefix="pwmsong_preview_") as temp_dir:
        preview_path = Path(temp_dir) / "preview.wav"
        _write_preview_wav(records, preview_path)
        # PlaySound is synchronous by default. SND_SYNC is not exposed by
        # winsound on some Python 3.8 Windows builds, so do not reference it.
        flags = winsound.SND_FILENAME
        count = 0
        while repeat == 0 or count < repeat:
            count += 1
            print(f"Playing preview {count}{'/' + str(repeat) if repeat else ''}...", flush=True)
            winsound.PlaySound(str(preview_path), flags)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Play a binary PWM Song file generated by SnailManager."
    )
    parser.add_argument("file", type=Path, help="Path to the .pwm_song file")
    parser.add_argument(
        "--repeat",
        type=int,
        default=1,
        help="Number of times to repeat; 0 means repeat forever (default: 1)",
    )
    parser.add_argument(
        "--list",
        action="store_true",
        help="Only list records; do not play them",
    )
    parser.add_argument(
        "--beep",
        action="store_true",
        help="Use winsound.Beep instead of a normal WAV audio preview",
    )
    args = parser.parse_args()

    if args.repeat < 0:
        parser.error("--repeat must be zero or a positive integer")
    if not args.file.is_file():
        print(f"File not found: {args.file}", file=sys.stderr)
        return 2

    try:
        records = read_pwmsong(args.file)
        total_ms = sum(duration for _, duration in records)
        print(f"File: {args.file}")
        print(f"Records: {len(records)}, duration: {total_ms / 1000.0:.2f} s")
        if args.list:
            for index, (frequency, duration) in enumerate(records, 1):
                print(f"{index:4}: {frequency:5} Hz, {duration:5} ms")
            return 0
        play_pwmsong(records, args.repeat, args.beep)
    except KeyboardInterrupt:
        print("\nPlayback stopped.")
        return 130
    except (OSError, RuntimeError, ValueError) as error:
        print(f"Error: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    # python tools\play_pwmsong.py "D:\Workspace\OpenWorkspace\SnailHeater\Tool\SnailManager\Generate\Cache\Wallpaper\3000万年前的迪迦童年珍贵片段_5.pwm_song"
    # python tools\play_pwmsong.py "D:\Workspace\OpenWorkspace\SnailHeater\Tool\SnailManager\Generate\Cache\Wallpaper\可爱又迷人的反派角色_清晰 480P.pwm_song"
    raise SystemExit(main())
